### ISSUE TITLE
“LSTM_extract.py” problem

### ISSUE THREAD

**Issue by zzf77** [weir12/DENA#10]
Hi,
I tried to run this command in step 3: 
python3 LSTM_extract.py --fast5 ${fast5_fn}  --corr_grp ${RawGenomeCorrected_000} --bam ${bam_fn}  --sites ${candidate_predict_pos.txt} --label ${any meaningful string} --windows 2 2

I used the command: python3 LSTM_extract.py --fast5 con-output/workspace/0/ --corr_grp ./con-output/RawGenomeCorrected_001 --bam ./con-basecalls.bam --sites ./candidate_predict_pos.txt --label LSTM-control --windows 2 2

But I received the following message:
Warning: The BRI module could not be loadedUsage: LSTM_extract.py [-h] {get_pos,predict} ...
LSTM_extract.py: Error: argument command: invalid choice: 'con-output/workspace' (choose from 'get_pos', 'predict')

 How could I resolve it? Thanks!
ZFZHANG

**Comment by weir12** [comment]
Hi:
Sorry for my late reply.
Please add `predict` as a subcommand after `LSTM_extract.py`.
For example：
`python3 LSTM_extract.py predict --fast5 con-output/workspace/0/ --corr_grp ./con-output/RawGenomeCorrected_001 --bam ./con-basecalls.bam --sites ./candidate_predict_pos.txt --label LSTM-control --windows 2 2`

Weir

**Comment by zzf77** [comment]
thank you！---- Replied Message ----FromLiang ***@***.***>Date04/07/2022 19:45 ***@***.***> ***@***.******@***.***>SubjectRe: [weir12/DENA] “LSTM_extract.py” problem (Issue #10)

Hi:

Sorry for my late reply.

Please add predict as a subcommand after LSTM_extract.py.

For example：

python3 LSTM_extract.py predict --fast5 con-output/workspace/0/ --corr_grp ./con-output/RawGenomeCorrected_001 --bam ./con-basecalls.bam --sites ./candidate_predict_pos.txt --label LSTM-control --windows 2 2

Weir



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/weir12/DENA/issues/10#issuecomment-1091635571",

"url": "https://github.com/weir12/DENA/issues/10#issuecomment-1091635571",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
