### ISSUE TITLE
LSTM_extract.py predict output nothing

### ISSUE THREAD

**Issue by William-chen777** [weir12/DENA#11]
Dear professor:
         when i use the commond:
`python ./DENA-release/step4_predict/LSTM_extract.py predict --fast5 ./singleFast5/ --corr_grp RawGenomeCorrected_000 --bam ./col.sorted.bam --sites ../candidate_predict_pos.txt --label col --windows 2 2 --processes 20`

I get some tmp files, but 3_tmp has nothing.
    625867 0_tmp
    709963 10_tmp
    678042 11_tmp
     73825 12_tmp
    701523 14_tmp
    682437 15_tmp
    691647 17_tmp
    663647 18_tmp
    651893 1_tmp
         0 3_tmp
    559607 4_tmp
    612549 5_tmp
    757275 6_tmp
    706120 7_tmp
       151 8_tmp
    522064 9_tmp

And this causes the process to go to sleep.
415378 ?        S      0:00 python 

What can I do for this problem?

Best wishes.

**Comment by defendant602** [comment]
I  have encontered the same problem, the command hangs after outputing some tmp files.

```
python3 LSTM_extract.py predict --processes 10 --fast5 fast5_pass_single --corr_grp RawGenomeCorrected_000 --bam basecalls.bam --sites candidate_predict_pos.txt --label sample --windows 2 2
```

**Comment by weir12** [comment]
Hi,
You can safely terminate these processes (including sub-processes), after confirming that the progress bar has reached 100% (add the "`--debug`" option to activate the progress bar)
Liang Ou
