### ISSUE TITLE
ouput explaination of LSTM_predict.py

### ISSUE THREAD

**Issue by defendant602** [weir12/DENA#12]
HI,
      Thanks for the great work you've done! I am using this software and get two tsv files after runing LSTM_predict.py.

   As shown in the mainpage, the tsv files have transcript id and m6A sites, but what do the rest columns mean ?  would appreciate some more detained explainations about the output files.

      Thanks.

**Comment by q1134269149** [comment]
Hi,

Thank you very much for your advice. For example:
_AT1G01010.1     30      AAACA   0       3       0.0
AT1G01010.1     212     AAACA   0       5       0.0
AT1G01010.1     341     AAACA   1       5       0.2_

**First column:** Transcript ID;
**Second column:** Transcriptional coordinate of  the central "A" base in RRACH motif;
**Third column:** Motif of candidate sites；
**Fourth column:** The number of modified reads;
**Fifth column:** The number of total reads;
**Sixth column:** The m6A ratio predicted at this site.

If our tools are helpful to you, please help us light up the Star in Github. Thank you！

qinhang

**Comment by weir12** [comment]
Hi,
Thank you for your interest in our project.

![image](https://user-images.githubusercontent.com/37523816/166450780-7c8be84d-5e78-4503-9bd6-aeb8ff1463c8.png)

This image may help explain the last three columns of the output file.
Please feel free to contact us whenever you have a question.
Liang Ou

**Comment by zzf77** [comment]
> Hi,
> 
> Thank you very much for your advice. For example: _AT1G01010.1 30 AAACA 0 3 0.0 AT1G01010.1 212 AAACA 0 5 0.0 AT1G01010.1 341 AAACA 1 5 0.2_
> 
> **First column:** Transcript ID; **Second column:** Transcriptional coordinate of the central "A" base in RRACH motif; **Third column:** Motif of candidate sites； **Fourth column:** The number of modified reads; **Fifth column:** The number of total reads; **Sixth column:** The m6A ratio predicted at this site.
> 
> If our tools are helpful to you, please help us light up the Star in Github. Thank you！
> 
> qinhang

Hi,
Thank you for your tools, but I have two questions about the result of this step.
Is the tsv file format the same as the bed format? Does the second column of the tsv files start at 0 or 1?
Due to I need to use the bedtools next, which requires the files in the format of bed.
Thanks!
