### ISSUE TITLE
Araport11 transcriptome for control 

### ISSUE THREAD

**Issue by JBerthelier** [weir12/DENA#16]
‌Dear DENA team, 
I am opening issue because the email [liangou@ips.ac.cn] do not works. I got my email back.

I would like to know wich Araport11 version you used in the DENA paper ?
Could you send me the link where you dowload it ?

I would like to repeat your analyses of m6A calling from your Col-0 data and compare with your output in Suplementary data to see if my installation and running of DENA is correct.

Best wiches,

Jeremy

**Comment by weir12** [comment]
Here is TAIR11 download link
https://www.arabidopsis.org/download_files/Genes/Araport11_genome_release/Araport11_blastsets/Araport11_cdna_20220914.gz
[liangou@ips.ac.cn](mailto:liangou@ips.ac.cn) Email has been deprecated because my employment status has changed

**Comment by JBerthelier** [comment]
I forgot to replied, but thanks it was useful !!
