### ISSUE TITLE
Potential issue with re-sqguiggle step

### ISSUE THREAD

**Issue by JBerthelier** [weir12/DENA#21]
Dear DENA author, 

I have a potential issue when I run the tombo re-sqguiggle step, 
I lost around half of my reads that cannot pass the re-sqguiggle step.
Is that expected? Did you face to this issue? Do you have an idea what could be the cause.
I am using the same transcriptome of Arabidopsis you used.

I already checked potential solution on Tombo "issue" but found no solution/explaination.

I got something like that below:

100%|▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒| 2977277/2977277 [14:30:45<00:00, 56.99it/s]
[07:12:26] Final unsuccessful reads summary (49.4% reads unsuccessfully processed; 1470935 total reads):
    47.8% (1422467 reads) : Alignment not produced
     1.6% (  46193 reads) : Poor raw to expected signal matching (revert with `tombo filter clear_filters`)
     0.1% (   2264 reads) : Read event to sequence alignment extends beyond bandwidth
     0.0% (      7 reads) : Reference mapping contains non-canonical bases (transcriptome reference cannot contain U bases)
     0.0% (      2 reads) : Not enough raw signal around potential genomic deletion(s)
     0.0% (      2 reads) : Fastq slot not present in --basecall-group

Otherwise all the steps from your tool DENA works perfectly!

Hope you can help me for that.

**Comment by weir12** [comment]
Hi,

Thank you for expressing interest in our project. I believe this issue may be attributed to a problem with `tombo`. Perhaps we should seek assistance from @marcus1487 to resolve it, or have you examined the success rate of alignment using `minimap2` alignment on transcriptome files? This factor greatly influences and contributes to the occurrence of `Alignment not produced`

Best wishes,

Liang
