### ISSUE TITLE
Issues with DENA's output

### ISSUE THREAD

**Issue by mumdark** [weir12/DENA#22]
#### 1.Some tmp files are empty during feature extraction.

![image](https://github.com/weir12/DENA/assets/83895347/db1ad7aa-c04a-42c3-987f-0e46f0ccde12)

#### 2.The total reads in the final result table are low. Were some reads filtered out?

![image](https://github.com/weir12/DENA/assets/83895347/f6a99a31-75ee-405c-a89d-7609b43fd2f1)

**Comment by weir12** [comment]
If only some of the intermediate files are empty, it typically does not indicate an error.

Please check the preprocessing and alignment results of Tombo and Minimap separately, especially the coverage of the regions you are interested in.

**Comment by mumdark** [comment]
@weir12 Thank you for your response. I have employed the same Tombo and Minimap analysis, and it seems that the read count in the DENA results has decreased. However, the read statistics in other software, such as nanom6A, appear to be normal. And these predicted results of DENA are largely consistent with those from other software.
