### ISSUE TITLE
3106 sites in Arabidopsis thaliana in the article

### ISSUE THREAD

**Issue by hanyishui0612** [weir12/DENA#26]
Hi，thank you for your great job!
When reading your article, I noticed that you obtained 3106 sites in Arabidopsis through preprocessing, and obtained unmodified sites and modified sites from the vir1 mutant and VIRC complement respectively.
 Now I  need the unmodified and modified sites of vir1 and VIRc, but the computer has limited storage and cannot store too much data.
Could you please share these 3106 sites? 
Looking forward to your reply！

**Comment by q1134269149** [comment]
Hi,

     Please refer to the issues section of DENA's GitHub website, the link is as follows:  https://github.com/weir12/DENA/issues/9. or: #9
Thanks!

Kind regards,
Hang Qin

**Comment by q1134269149** [comment]
Hi,

Please refer to the issues of #9, thanks!

Kind regards,
Hang Qin

**Comment by hanyishui0612** [comment]
> Hi,
> 
> Please refer to the issues of #9, thanks!
> 
> Kind regards, Hang Qin

Thank you for your reply.Now I have a question, what does the last column of this file (m6A) represent
~~~
transid	geneid	strand	m6A
AT5G67590.1	AT5G67590	+	787
AT5G67590.1	AT5G67590	+	733
AT5G67560.1	AT5G67560	+	1156
AT5G67560.1	AT5G67560	+	1126
AT5G67510.1	AT5G67510	+	677
~~~

**Comment by hanyishui0612** [comment]
I have two more questions．
１，Does the basecalling reads here refer to fastq files?
２，How can I check if VIRc sample or vir1 sample contains a mismatch?
![DENA](https://github.com/user-attachments/assets/c08a3653-3b5e-4ac9-9dd9-90d36a40d8d2)

**Comment by q1134269149** [comment]
Hi, 

The last column represents transcriptome locus. The mismatch was checked in fastq files basecalled from fast5 files using Guppy.

Kind regards,
Hang Qin

**Comment by hanyishui0612** [comment]
> Hi,
> 
> The last column represents transcriptome locus. The mismatch was checked in fastq files basecalled from fast5 files using Guppy.
> 
> Kind regards, Hang Qin

thank you for your reply！According to what you mean, does the last column represent the position of the site on the transcript?Can you tell me how to check mismatch against fastq file？I have one more question:Do you know how to get site-level labels from Parker？（Parker, M. T. et al. Nanopore direct RNA sequencing maps
the complexity of Arabidopsis mRNA processing and m6A
modification.）
