### ISSUE TITLE
Missing import pandas as pd in LSTM_predict.py

### ISSUE THREAD

**Issue by FDallaPozza** [weir12/DENA#7]
Hi,
I tried to run this command: 

python LSTM_predict.py -i ${path_features} -m ${path_models} -o ${path_output} -p ${prefix_outfile} -d 

and the -d option require the creation of a pandas data frame, however it seems that the LSTM_predict.py code doesn't do it, I had to modify and add "import pandas as pd" to avoid this error. Just to let you know. 

Fabio

**Comment by weir12** [comment]
Hi,
Thanks for catching the problem and giving feedback in time!
I have fixed it.
Weir
