### ISSUE TITLE
Abnormal result: The prediction output file is empty

### ISSUE THREAD

**Issue by Derryxu** [weir12/DENA#8]
Hi,
I tried to use DENA  pre-train model to predict m6A of my data, I followed  the step 4 (prediction) on my data.However, the output file both result.tsv and result_details.tsv are empty. It seems data problem, so I check extracted features file:
1.  the candidate_predict_pos.txt
```
cc6m_2244_T7_ecorv	57	62	+	AAACC
cc6m_2244_T7_ecorv	64	69	+	GGACC
cc6m_2244_T7_ecorv	100	105	+	GGACT
cc6m_2244_T7_ecorv	121	126	+	GGACC
cc6m_2244_T7_ecorv	173	178	+	AGACT
```
2. the features tmp file
```
>cc6m_2595_T7_ecorv_724_GAACC
adec290a-fa23-4951-9863-51c26c65ab5e	15.0,5.0,2.0,3.0,4.0,116.0,12.0,29.0,19.0,6.0,2.05947621375705,0.05645722345324113,-0.6669842273497038,-1.1006984040938008,-0.04247432038586929,1.896162953567763,0.0775064880998608,-0.7244704949363322,-1.1033572585754785,-0.061418658567826176,nan,nan,nan,nan,nan
fb801573-cb5c-4303-bc93-2a03078640d3	37.0,36.0,43.0,39.0,27.0,54.0,47.0,15.0,19.0,139.0,2.1592956780773624,0.21144323911696417,-0.5459008501149659,-1.3049430979691616,-0.14210523308214737,2.103417210260246,0.19766736049756647,-0.5841787317127636,-1.3049430979691616,-0.1443903048444529,nan,nan,nan,nan,nan
0c957530-bdeb-4fe8-831b-7af44316226b	24.0,26.0,26.0,26.0,19.0,53.0,29.0,23.0,16.0,6.0,1.6108504242449508,0.3408191542598859,-0.5112268966474004,-1.0857024459872902,0.07775649380342814,1.389964503297866,0.19353955346470164,-0.47542923568932577,-1.073641710605908,0.019864963972790688,nan,nan,nan,nan,nan
```
3. I also print the intermediate variable predict_label, all nan
```
predict_label
tensor([[nan, nan],
        [nan, nan],
        [nan, nan],
        ...,
        [nan, nan],
        [nan, nan],
        [nan, nan]])
......
```
How could I resolve it? Thanks in advance.

**Comment by weir12** [comment]
Hi，
I noticed that the last five columns of the feature table are missing values, which should have been the current standard deviation. My guess is that you maybe forgot to add` --include-event-stdev`  to the` tombo re-sguiggle` command option.
I suggest you re-run` tombo re-sguiggle` command and add this option.I will add this note to the DENA readme
For an explanation of this parameter, please refer to https://nanoporetech.github.io/tombo/resquiggle.html
best wishes
weir

**Comment by Derryxu** [comment]
Hi,
Thank you very much for your reply. I'll re-run `tombo re-sguiggle` command with the option `--include-event-stdev` and close the issue after finishing all my data if there have no further errors.
Best wishes.
xu
