### ISSUE TITLE
The common m6A sites

### ISSUE THREAD

**Issue by Derryxu** [weir12/DENA#9]
Hi,
As the paper shown,  3106 common m6A sites identified by differr tool across Cm, Cf, and Vv, Could this sites list file be shared please? Is there any way can obtain it? Thanks in advance.
xu

**Comment by q1134269149** [comment]
[final_overlep_sites.txt](https://github.com/weir12/DENA/files/8385906/final_overlep_sites.txt)

**Comment by Derryxu** [comment]
Hi,
Thank you very much. Best wishes to you.
xu
